config/routes.rb
Rails.application.routes.draw do
  #ルートpassを受け取った際に、postsコントローラーのindexアクションを使用する
  root to: "questions#index"
  #questionsというurlを受け取った際のアクションとして、index,new,createのいずれかアクションを許可
  resources :questions, only: [:index, :new, :create]
  #questionの詳細表示から、answerコントローラーを操作可能
  resources :questions, only: :show do
    resources :answers, only: [:index, :new, :create]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = Answer.create(answer_param)
    redirect_to question_path(@answer.question_id)
  end

  private

  def answer_param
    params.require(:answer).permit(:content, :user_name).merge(question_id: params[:question_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index # indexアクションを定義した
    @questions = Question.all # すべてのレコードを@questionsに代入
  end

  def new
    @question = Question.new
  end

  def create
    Question.create(question_params)
    redirect_to root_path
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @answer = Answer.new
  end

  private

  def question_params
    params.require(:question).permit(:title, :content, :user_name)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_index.html.erb
<% answers.each do |answer|%>
  <div class="question">
    <div class="question-main">
      <div class="question-content">
        <%=answer.content%>
      </div>
      <div class="question-user-name">
        <%=answer.user_name%>
      </div>
    </div>
  </div>
<% end %>

app/views/answers/_new.html.erb
<%= form_with(model:answer,url:question_answers_path(question.id),local:true) do |form| %>
  <%= form.text_area :content, placeholder: "投稿内容" %>
  <%= form.text_field :user_name, placeholder: "投稿者名" %>
  <%= form.submit "POST" ,class:"btn-question"%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeckChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header>
      <%=link_to "TechChat",root_path,class:"title"%>
      <%=link_to "質問する",new_question_path,class:"new-question"%>
    </header>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <%= form.text_field :title, placeholder: "タイトル" %>
  <%= form.text_area :content, placeholder: "投稿内容" %>
  <%= form.text_field :user_name, placeholder: "投稿者名" %>
  <%= form.submit "POST" ,class:"btn-question"%>
<% end %>

app/views/questions/_question.html.erb
<div class="question">
  <div class="question-sidebar">
    <div class="comments-num">
      0
    </div>
    <div class="sidebar-title">
      comments
    </div>
  </div>
  <div class="question-main">
    <div class="question-header">
      <div class="question-title">
        <%=link_to question.title,question_path(question.id)%>
      </div>
      <div class="question-user-name">
        <%=question.user_name%>
      </div>
    </div>
    <div class="question-content">
      <%=question.content%>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<main>
  <div class="questions">
    <% @questions.each do |question| %>
      <%=render partial:"question" ,locals:{question:question} %>
    <% end %>
  </div>
</main>

app/views/questions/new.html.erb
<main class="new">
  <div class="question-form">
    <div class="question-form-header"></div>
    <div class="question-form-main">
      <%=render partial:"form" ,locals:{question:@question} %>
    </div>
  </div>
</main>

app/views/questions/show.html.erb
<main class="show">
  <div class="questions">
    <%=render partial:"question" ,locals:{question:@question} %>
  </div>
  <div class="questions">
    <%=render partial: "answers/index",locals:{answers:@answers}%>
  </div>
  <div class="question-form">
    <%=render partial: "answers/new",locals:{answer:@answer,question:@question}%>
  </div>
</main>